version: '3.8'
services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    restart: always
    ports:
      - "1880:1880"
    networks:
      db-api-net:
        ipv4_address: 10.16.1.6
    volumes:
      - node-red-data:/data

  db:
    image: mongo:latest
    container_name: nutMongo
    env_file:
      - ./.env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb:/data/db
    networks:
      db-api-net:
        ipv4_address: 10.16.1.2
    ports:
      - "27017:27017"
  
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: floodapi
    env_file:
      - ./.env
    environment:
      PORT: 8899
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    depends_on:
      - db
    volumes:
      - ./api/src:/api:rw
      - ./api/images:/images:rw
    restart: "no"
    networks:
      db-api-net:
        ipv4_address: 10.16.1.3
    ports:
      - "8899:80"
    
  mqtt:
    build:
      context: mqtt
    container_name: floodmqtt
    volumes:
      - emqxlog:/opt/emqx/log
      - emqxdata:/opt/emqx/data
    networks:
      db-api-net:
        ipv4_address: 10.16.1.5
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "11883:11883"
      - "18083:18083"
      - "4370:4370"
      - "5369:5369"

volumes:
  mongodb:
  emqxlog:
  emqxdata:
  node-red-data:


networks:
  db-api-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.16.1.0/24
          gateway: 10.16.1.1